import { cn } from '@/lib/utils';
import type { Metadata } from 'next';
import { Nunito } from 'next/font/google';
import './globals.css';
import { QueryClientWrapper } from '@/lib/query-client-wrapper';
import { ReduxProviderWrapper } from '@/lib/redux-provider-wrapper';

const nunito = Nunito({
  variable: '--font-nunito',
  subsets: ['latin'],
  weight: ['400', '500', '600', '700', '800'],
  style: ['normal', 'italic'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body className={cn(nunito.variable, 'antialiased')}>
        <ReduxProviderWrapper>
          <QueryClientWrapper>
            <div className='bg-neutral-25 flex min-h-screen flex-col'>
              {children}
            </div>
          </QueryClientWrapper>
        </ReduxProviderWrapper>
      </body>
    </html>
  );
}
